# Generated by Django 4.2.7 on 2025-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magnets", "0002_alter_magnetlink_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="magnetlink",
            name="source",
            field=models.CharField(
                default="unknown",
                help_text="如: avmoo, javbus, javlibrary",
                max_length=50,
                verbose_name="数据来源",
            ),
        ),
    ]
