# Generated by Django 4.2.7 on 2025-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="女友/演员的姓名", max_length=100, verbose_name="姓名"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="英文或罗马音姓名",
                        max_length=100,
                        verbose_name="英文名",
                    ),
                ),
                (
                    "alias",
                    models.TextField(
                        blank=True, help_text="其他别名，用逗号分隔", verbose_name="别名"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="身高(cm)"
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="体重(kg)"
                    ),
                ),
                (
                    "measurements",
                    models.CharField(
                        blank=True,
                        help_text="例如：B88-W58-H85",
                        max_length=50,
                        verbose_name="三围",
                    ),
                ),
                (
                    "cup_size",
                    models.CharField(blank=True, max_length=10, verbose_name="罩杯"),
                ),
                (
                    "blood_type",
                    models.CharField(blank=True, max_length=5, verbose_name="血型"),
                ),
                (
                    "nationality",
                    models.CharField(default="日本", max_length=50, verbose_name="国籍"),
                ),
                (
                    "debut_date",
                    models.DateField(blank=True, null=True, verbose_name="出道日期"),
                ),
                (
                    "retirement_date",
                    models.DateField(blank=True, null=True, verbose_name="引退日期"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "agency",
                    models.CharField(blank=True, max_length=100, verbose_name="所属事务所"),
                ),
                (
                    "profile_image",
                    models.URLField(
                        blank=True,
                        help_text="个人头像图片URL",
                        max_length=500,
                        verbose_name="头像",
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True,
                        help_text="个人封面图片URL",
                        max_length=500,
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "gallery_images",
                    models.TextField(
                        blank=True, help_text="多张图片URL，用换行分隔", verbose_name="图片集"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="个人简介")),
                (
                    "specialties",
                    models.TextField(
                        blank=True, help_text="个人特色、擅长类型等", verbose_name="特长/特色"
                    ),
                ),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("blog", models.URLField(blank=True, verbose_name="博客/官网")),
                (
                    "popularity_score",
                    models.PositiveIntegerField(default=0, verbose_name="人气值"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "favorite_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏次数"),
                ),
                (
                    "movie_count",
                    models.PositiveIntegerField(default=0, verbose_name="作品数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "女友/演员",
                "verbose_name_plural": "女友/演员管理",
                "ordering": ["-popularity_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActressTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名称"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="标签别名")),
                ("description", models.TextField(blank=True, verbose_name="标签描述")),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="十六进制颜色代码，如 #007bff",
                        max_length=7,
                        verbose_name="标签颜色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "actresses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags",
                        to="actresses.actress",
                        verbose_name="关联女友",
                    ),
                ),
            ],
            options={
                "verbose_name": "女友标签",
                "verbose_name_plural": "女友标签管理",
                "ordering": ["name"],
            },
        ),
    ]
