# Generated by Django 4.2.7 on 2025-07-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actresses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actress",
            name="crawl_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="爬取日期"),
        ),
        migrations.AddField(
            model_name="actress",
            name="movies_crawled",
            field=models.BooleanField(default=False, verbose_name="是否已爬取作品"),
        ),
    ]
