# Generated by Django 4.2.7 on 2025-07-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actresses", "0002_actress_crawl_date_actress_movies_crawled"),
    ]

    operations = [
        migrations.AddField(
            model_name="actress",
            name="lifestyle_photos",
            field=models.TextField(
                blank=True, help_text="生活照片URL，用换行分隔", verbose_name="生活照"
            ),
        ),
        migrations.AddField(
            model_name="actress",
            name="portrait_photos",
            field=models.TextField(
                blank=True, help_text="写真照片URL，用换行分隔", verbose_name="写真照"
            ),
        ),
    ]
