# Generated by Django 4.2.7 on 2025-07-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actresses", "0003_actress_lifestyle_photos_actress_portrait_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="actress",
            name="cover_image_local",
            field=models.CharField(
                blank=True, help_text="本地封面图片路径", max_length=500, verbose_name="本地封面路径"
            ),
        ),
        migrations.AddField(
            model_name="actress",
            name="lifestyle_photos_local",
            field=models.TextField(
                blank=True, help_text="本地生活照片路径，用换行分隔", verbose_name="本地生活照路径"
            ),
        ),
        migrations.AddField(
            model_name="actress",
            name="portrait_photos_local",
            field=models.TextField(
                blank=True, help_text="本地写真照片路径，用换行分隔", verbose_name="本地写真照路径"
            ),
        ),
        migrations.AddField(
            model_name="actress",
            name="profile_image_local",
            field=models.CharField(
                blank=True, help_text="本地头像图片路径", max_length=500, verbose_name="本地头像路径"
            ),
        ),
    ]
