# Generated by Django 4.2.7 on 2025-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actresses", "0004_actress_cover_image_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actress",
            name="crawl_count",
            field=models.PositiveIntegerField(default=0, verbose_name="爬取次数"),
        ),
        migrations.AddField(
            model_name="actress",
            name="crawl_depth",
            field=models.PositiveIntegerField(
                default=0, help_text="在递归爬取中的深度层级", verbose_name="爬取深度"
            ),
        ),
        migrations.AddField(
            model_name="actress",
            name="last_crawled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后爬取时间"),
        ),
        migrations.AddField(
            model_name="actress",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="女友详情页URL", max_length=500, verbose_name="来源URL"
            ),
        ),
    ]
