# Generated by Django 4.2.7 on 2025-07-20 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "censored_id",
                    models.CharField(
                        db_index=True,
                        help_text="影片的唯一编号，如 YMLW-047",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="影片编号格式不正确，应为类似 YMLW-047 的格式",
                                regex="^[A-Z0-9]+-\\d+$",
                            )
                        ],
                        verbose_name="影片编号",
                    ),
                ),
                (
                    "movie_title",
                    models.TextField(
                        blank=True, help_text="影片的完整标题", verbose_name="影片标题"
                    ),
                ),
                (
                    "movie_pic_cover",
                    models.URLField(
                        blank=True,
                        help_text="影片封面图片URL",
                        max_length=500,
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="发行日期"),
                ),
                (
                    "movie_length",
                    models.CharField(
                        blank=True,
                        help_text="如: 120分钟",
                        max_length=20,
                        verbose_name="影片时长",
                    ),
                ),
                (
                    "director",
                    models.CharField(blank=True, max_length=100, verbose_name="导演"),
                ),
                (
                    "studio",
                    models.CharField(blank=True, max_length=100, verbose_name="制作商"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="发行商"),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="系列"),
                ),
                (
                    "genre",
                    models.TextField(
                        blank=True, help_text="多个类型用逗号分隔", verbose_name="类型"
                    ),
                ),
                (
                    "jav_idols",
                    models.TextField(
                        blank=True, help_text="多个演员用逗号分隔", verbose_name="演员"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("avmoo", "Avmoo"),
                            ("javbus", "Javbus"),
                            ("javlibrary", "Javlibrary"),
                        ],
                        default="javbus",
                        max_length=20,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "code_36",
                    models.CharField(
                        blank=True,
                        help_text="用于内部标识的36进制编码",
                        max_length=10,
                        verbose_name="36进制编码",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "影片",
                "verbose_name_plural": "影片",
                "db_table": "movies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名称"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="标签别名")),
                ("description", models.TextField(blank=True, verbose_name="标签描述")),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="十六进制颜色代码",
                        max_length=7,
                        verbose_name="标签颜色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "movies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags",
                        to="movies.movie",
                        verbose_name="关联影片",
                    ),
                ),
            ],
            options={
                "verbose_name": "影片标签",
                "verbose_name_plural": "影片标签",
                "db_table": "movie_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MovieRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=3, verbose_name="平均评分"
                    ),
                ),
                (
                    "total_votes",
                    models.PositiveIntegerField(default=0, verbose_name="总投票数"),
                ),
                (
                    "five_star",
                    models.PositiveIntegerField(default=0, verbose_name="5星"),
                ),
                (
                    "four_star",
                    models.PositiveIntegerField(default=0, verbose_name="4星"),
                ),
                (
                    "three_star",
                    models.PositiveIntegerField(default=0, verbose_name="3星"),
                ),
                ("two_star", models.PositiveIntegerField(default=0, verbose_name="2星")),
                ("one_star", models.PositiveIntegerField(default=0, verbose_name="1星")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="movies.movie",
                        verbose_name="影片",
                    ),
                ),
            ],
            options={
                "verbose_name": "影片评分",
                "verbose_name_plural": "影片评分",
                "db_table": "movie_ratings",
            },
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["censored_id"], name="movies_censore_759162_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["source"], name="movies_source_09727a_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date"], name="movies_release_e1d0b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["created_at"], name="movies_created_eae010_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["view_count"], name="movies_view_co_c1a961_idx"),
        ),
    ]
