# Generated by Django 4.2.7 on 2025-07-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actresses", "0001_initial"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actresses",
            field=models.ManyToManyField(
                blank=True,
                help_text="参演此影片的女友",
                related_name="movies",
                to="actresses.actress",
                verbose_name="关联女友",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_tags",
            field=models.TextField(
                blank=True, help_text="影片的特殊标记或标签，用逗号分隔", verbose_name="影片标记"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="sample_images",
            field=models.TextField(
                blank=True, help_text="影片样例图片URL，多个URL用换行分隔", verbose_name="样例图片"
            ),
        ),
    ]
