# Generated by Django 4.2.7 on 2025-07-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_actresses_movie_movie_tags_movie_sample_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="影片时长，以分钟为单位", null=True, verbose_name="时长(分钟)"
            ),
        ),
    ]
