# Generated by Django 4.2.7 on 2025-07-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movie_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cover_image",
            field=models.URLField(
                blank=True, help_text="作品封面图片URL", max_length=500, verbose_name="作品封面"
            ),
        ),
    ]
