# Generated by Django 4.2.7 on 2025-07-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_movie_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cover_image_local",
            field=models.CharField(
                blank=True, help_text="本地封面图片路径", max_length=500, verbose_name="本地封面路径"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="sample_images_local",
            field=models.TextField(
                blank=True, help_text="本地样品图片路径，用换行分隔", verbose_name="本地样品图路径"
            ),
        ),
    ]
